Show balance
stablecoinhq/stable-web pull request #30
Opened 2022-11-16 05:57 UTC by HirotoShioi

Mint/Burn画面にてトークンの残高を表示させる。

https://github.com/stablecoinhq/stable-web/pull/29
と同様Vault操作時に数量を反映させるようにする

2022-11-16 05:59 UTC, HirotoShioi commented
![スクリーンショット 2022-11-16 14 58 52](https://user-images.githubusercontent.com/15665039/202096216-676c1caf-cbf2-438d-b5fd-9a44428404b6.png)

2022-11-21 07:10 UTC, HirotoShioi commented
![スクリーンショット 2022-11-21 16 10 01](https://user-images.githubusercontent.com/15665039/202987025-163fcfe5-8d94-479c-b843-1b3cad630fef.png)

2022-11-21 07:18 UTC, HirotoShioi commented
Vault作成画面及びMint/Burn画面に担保となる通貨の残高を表示させるようにしました。

2022-11-22 05:45 UTC, HirotoShioi commented
担保率を表示させるようにした。

![スクリーンショット 2022-11-22 14 43 24](https://user-images.githubusercontent.com/15665039/203234458-cf25b74e-346f-4120-887c-5c0edff44144.png)

2022-11-22 16:01 UTC, kyori19 requested changes
画面上の動作については確認しましたが、Collateral Ratioの計算については @tgfukuda さんのダブルチェックをお願いしたいです。

2022-11-24 01:13 UTC, HirotoShioi commented on pages/vaults/[id]/index.page.tsx
> +      />
@kyori19 

> DAIの残高とGemの残高の双方を常時表示しても良いと思うのですが、切り替える形にしたのはなぜでしょうか？タブを切り替えるとタブより上にあるカードの表示が変化するのは違和感があるので、もしやるのであればタブの下に置くのが良いのではないでしょうか。

2つ理由があります。

1. 両方表示だとVault開設画面にてDAI残高というVault開設には余計な情報が表示されてしまう。
2. Mint時も正直DAI残高情報というは余計な情報でしかない。ユーザーにとって大事なのはMint時に利用するトークンの残高であって、DAI残高ではない。

> 設計の観点からも、コンポーネント切り分けの観点から意図的にタブに関する状態を外部に見せないように Controller **内に閉じているので、この変更は好ましくないと考えています。タブの制御を外部のコンポーネントに委ねるのは、外部の実装次第でタブを切り替えられなくすることも可能となり、責務の分割に失敗していると考えられます。**

なのであれば残高情報などを全てControllerコンポーネントに移動させるのは如何でしょうか

2022-11-24 01:19 UTC, HirotoShioi commented on contracts/VatHelper.ts
> +      collateralizationRatio: toFixedNumber(ink.mul(spot).mul(100).div(art.mul(rate)), FixedFormat.from(0)),
@kyori19 

> これはすでに取得できるIlkStatusとUrnStatusから計算できるので別の箇所で計算するようにすべきだと思います。計算式を独立させることでテストを書くことができるようになるほか、 https://github.com/stablecoinhq/stable-web/pull/28 にてBigNumberでの計算を禁止した恩恵を得ることができます。

これはどのようなテストを書く想定ですか？あまり意図が理解できません

> あと、小数部を切り捨てているのは意図的なものでしょうか？

はい！意図的です。Mint時のCollateralization ratioと表記を統一させようとしています。

2022-11-25 01:14 UTC, HirotoShioi commented on contracts/VatHelper.ts
> +      collateralizationRatio: toFixedNumber(ink.mul(spot).mul(100).div(art.mul(rate)), FixedFormat.from(0)),
計算式はこのコントラクトを参考にしています。
https://github.com/makerdao/dss/blob/master/src/dog.sol#L181

2022-11-25 03:26 UTC, HirotoShioi commented
Use memoを使う、0除算を防ぐ

2022-11-25 04:02 UTC, kyori19 commented on pages/vaults/[id]/index.page.tsx
> +      />
> > DAIの残高とGemの残高の双方を常時表示しても良いと思うのですが、切り替える形にしたのはなぜでしょうか？タブを切り替えるとタブより上にあるカードの表示が変化するのは違和感があるので、もしやるのであればタブの下に置くのが良いのではないでしょうか。
> 
> 2つ理由があります。
> 
> 1. 両方表示だとVault開設画面にてDAI残高というVault開設には余計な情報が表示されてしまう。
> 2. Mint時も正直DAI残高情報というは余計な情報でしかない。ユーザーにとって大事なのはMint時に利用するトークンの残高であって、DAI残高ではない。

1つめの理由については理解です。コンポーネントにDAI残高を非表示にするオプションを設ける形でどうでしょうか？
2点目についてはユーザーの視点がわかりませんが、タブを切り替えないとDAI残高が表示できないのは直感的ではないかなと個人的には思いました。初めて利用するユーザーは残高表示が切り替わったことに気づかない可能性もあるかと思います。

> > 設計の観点からも、コンポーネント切り分けの観点から意図的にタブに関する状態を外部に見せないように Controller 内に閉じているので、この変更は好ましくないと考えています。タブの制御を外部のコンポーネントに委ねるのは、外部の実装次第でタブを切り替えられなくすることも可能となり、責務の分割に失敗していると考えられます。
> 
> なのであれば残高情報などを全てControllerコンポーネントに移動させるのは如何でしょうか

そうですね、現状の実装であればController側に残高をもたせるのが自然に思います。

2022-11-25 04:06 UTC, kyori19 approved these changes
大体の動作は問題なさそうなのでApprove

2022-11-25 04:38 UTC, merged