[STAB-167][STAB-111][STAB-63] Show how amount of DAI will be minted
stablecoinhq/stable-web pull request #32
Opened 2022-11-21 09:04 UTC by HirotoShioi

Mint/Vault開設時に発行されるDAIの数量を表示させるようにしました。

2022-11-21 09:05 UTC, HirotoShioi commented
![スクリーンショット 2022-11-21 18 00 27](https://user-images.githubusercontent.com/15665039/203009479-c1a16105-80a7-435e-a231-a757bbfeb4d1.png)

2022-11-22 16:34 UTC, kyori19 reviewed
ゼロ除算のエラーでクラッシュする不具合があるので、修正をお願いします。( `0x0b` のウォレットなんですが、他人のウォレットを表示することを禁止しているのでデバッグのための情報としては微妙ですね)

```
Error: division-by-zero [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-division-by-zero ] (fault="division-by-zero", operation="div", code=NUMERIC_FAULT, version=bignumber/5.7.0)
```

2022-11-22 16:34 UTC, kyori19 commented on pages/forms/MintForm.tsx
> +  const [ratioText, setRatioText] = useState(initialRatio.toString());
`initialRatio` の計算は初回レンダリングのみでしか利用されないにも関わらずレンダリングのたびに計算されるので、パフォーマンス上の懸念があります。初期値にコストの高い計算が必要な場合、 `useState` に関数を渡すのが良いとされています。
https://reactjs.org/docs/hooks-reference.html#lazy-initial-state

それはさておき、初回表示後に `liquidationRatio` や `debtMultiplier` が遅れて到着・あるいは変化した際にratioが変化しないという問題があると思うのですが、良いのでしょうか？

2022-11-22 16:34 UTC, kyori19 commented on pages/forms/MintForm.tsx
> +    }
`useMemo` でなんの値も返さない場合というのはReactの仕様にない(未定義動作である)ようですので、必ず値を返すように変更お願いします。

2022-11-24 00:56 UTC, HirotoShioi commented on pages/forms/MintForm.tsx
> +        )}
> 値を入力すると画面がガクッとズレるのが気になります。常に表示して値がないときはグレーアウトするなどのほうが良いかと思います。

了解しました！

デザイン周りはあとで修正するので一旦無視します

2022-11-24 01:31 UTC, HirotoShioi commented on pages/forms/MintForm.tsx
> +        )}
> 値を入力すると画面がガクッとズレるのが気になります。常に表示して値がないときはグレーアウトするなどのほうが良いかと思います。

入力なしの場合は0を表示するようにしました。

2022-11-24 01:31 UTC, HirotoShioi commented on pages/forms/MintForm.tsx
> +        )}
> tooltipの説明文が誤っているかと思います。(totalではないので)

2022-11-24 01:35 UTC, HirotoShioi commented on pages/forms/MintForm.tsx
> +  const [ratioText, setRatioText] = useState(initialRatio.toString());
> それはさておき、初回表示後に liquidationRatio や debtMultiplier が遅れて到着・あるいは変化した際にratioが変化しないという問題があると思うのですが、良いのでしょうか？

遅れて到着ってどういうケースなのでしょうか。あとこの2つのパラメーターは滅多に変更されない（数ヶ月に1回程度）ので変化することは無視して良さそうです

2022-11-25 04:08 UTC, kyori19 commented
TODO: ゼロ除算の解決を確認

2022-11-25 05:04 UTC, HirotoShioi commented
rebaseして必要最低限のコミットのみにした

2022-11-25 14:51 UTC, kyori19 requested changes

2022-11-25 14:51 UTC, kyori19 commented on pages/forms/MintForm.tsx
> +    return FixedNumber.fromValue(BigNumber.from(0));
`FixedNumber.fromString` を用いるほうが良いと思います。 `FixedNumber` は内部で文字列として数値を保持しているので `BigNumber` オブジェクトを無駄に生成することになりますし、何桁まで保持するかの情報を与えていないのも気になりました。(デフォルトだと小数18桁だったような気がしますが明示的にすべきかと思います。)
`BigNumber` は使用しない流れにしているので特に理由がなければあわせたほうがいいかと思います。

2022-11-28 13:13 UTC, kyori19 approved these changes

2022-11-29 04:53 UTC, HirotoShioi commented
https://fressets.atlassian.net/browse/STAB-111
を取り組んでいる際に、DAIの算出方法が間違っていることが判明しました。
なのでその修正とともにSTAB-111及びSTAB-63の修正もこのPRに組み込みます。
https://fressets.atlassian.net/browse/STAB-111
https://fressets.atlassian.net/browse/STAB-63

2022-11-29 04:55 UTC, HirotoShioi commented on contracts/ProxyActionsHelper.ts
> +    if (ilkInfo.symbol === 'ETH') {
ここの分岐が間違っているせいでETHのVault操作が上手くできていなかった

2022-11-29 04:55 UTC, HirotoShioi commented on contracts/ProxyActionsHelper.ts
> +    if (ilkInfo.symbol === 'ETH') {
ここの分岐が間違っているせいでETHのVault操作が上手くできていなかった

2022-11-29 04:55 UTC, HirotoShioi commented on contracts/Vault.ts
> +  static getDaiAmount(colAmount: FixedNumber, liqRatio: FixedNumber, colRatio: FixedNumber, price: FixedNumber): FixedNumber {
DAI数量の算出方法が間違っていたので修正。

2022-11-29 07:47 UTC, HirotoShioi commented
何かがおかしい。一旦draftにする

2022-11-29 09:21 UTC, HirotoShioi commented
担保率の計算が間違っていたので修正。あとDAIの生成量も間違っていた
https://github.com/makerdao/developerguides/blob/master/vault/monitoring-collateral-types-and-vaults/monitoring-collateral-types-and-vaults.md#use-maker-protocol-parameters-for-calculations

2022-11-29 15:44 UTC, kyori19 submitted a review, later dismissed
計算式については理解しきれていないのでわからないですが、コードは問題ないと思います。

2022-11-30 00:44 UTC, HirotoShioi commented
@kyori19 お手数ですが、再度レビューお願いしますか。リベースしたら再度Approveが必要になりました。

2022-11-30 03:07 UTC, tgfukuda approved these changes

2022-11-30 03:07 UTC, merged